import fs from "node:fs";
import path from "node:path";

export function generateFlagsDts(flags: any[]) {
  const lines = [
    "// DO NOT EDIT THIS FILE.",
    "// GENERATED BY FLAGBASE CLI.",
    "",
    'import "@flagbase/react-sdk";',
    "",
    'declare module "@flagbase/react-sdk" {',
    "  export interface Flags {",
  ];

  for (const flag of flags) {
    const type =
      flag.type === "enum"
        ? flag.enumValues.map((v: string) => `"${v}"`).join(" | ")
        : flag.type;

    lines.push(`    "${flag.key}": ${type};`);
  }

  lines.push("  }", "}");

  const outDir = path.join(process.cwd(), "gen");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "flags.d.ts"), lines.join("\n"));
}
