import fs from "node:fs";
import path from "node:path";
import type { FlagDefinition } from "@flagbase/core";

export function generateFlagsDts(flags: FlagDefinition[]) {
  const lines = [
    "// DO NOT EDIT THIS FILE.",
    "// GENERATED BY FLAGBASE CLI.",
    "",
    'import "@flagbase/sdk";',
    "",
    'declare module "@flagbase/sdk" {',
    "  export interface Flags {",
  ];

  for (const flag of flags) {
    lines.push(`    "${flag.key}": boolean;`);
  }

  lines.push("  }", "}");

  const outDir = path.join(process.cwd(), "gen");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "flags.d.ts"), lines.join("\n"));
}
