packages:
  - apps/*
  - packages/*

catalog:
  '@polar-sh/better-auth': ^1.6.1
  '@prisma/client': ^7.1.0
  '@tailwindcss/postcss': ^4.1.18
  '@trpc/client': ^11.8.0
  '@trpc/server': ^11.8.0
  '@types/node': ^25.0.2
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  better-auth: ^1.4.7
  dotenv: ^17.2.3
  lucide-react: ^0.561.0
  next: 16.0.10
  react: 19.2.3
  react-dom: 19.2.3
  tailwindcss: ^4.1.18
  tsdown: ^0.17.4
  typescript: ^5.9.3
  zod: ^4.1.13
